# Base model location (local path or HF repo)
model:
  # Path to the Llama 3.1 8B base model. Change if you downloaded it locally.
  base_model_path: "meta-llama/Llama-3.1-8B"
  adapters: []  # List of adapter paths (optional)

