# Configuration for dataset preprocessing
# Each dataset entry specifies the input JSON file, output path, and optional template override

default_template: /workspace/data/mygitstuff/llama3_fine_tuning/configs/prompt_templates/default_nl_sql.json

datasets:
  - input: /workspace/data/mygitstuff/data_generator/generated_datasets/joins/dataset_v1.jsonl
    output: /workspace/data/mygitstuff/llama3_fine_tuning/datasets/preprocessed_joins.jsonl
  - input: /workspace/data/mygitstuff/data_generator/generated_datasets/schema_docs/dataset.jsonl
    output: /workspace/data/mygitstuff/llama3_fine_tuning/datasets/preprocessed_schema_docs.jsonl
    template: /workspace/data/mygitstuff/llama3_fine_tuning/configs/prompt_templates/nl_textsql.json
  # Add more datasets as needed
  # - input: path/to/other.json
  #   output: path/to/output.jsonl
  #   template: configs/prompt_templates/custom_template.json
