# Configuration for LoRA fine-tuning
model:
  # Path to the base model weights (local path or HF repo)
  base_model_path: /path/to/llama-3.1-8b
  hf_token: null  # Optional Hugging Face token

training:
  datasets:
    - /path/to/preprocessed_dataset1.jsonl
    - /path/to/preprocessed_dataset2.jsonl
  output_dir: checkpoints/lora_output
  num_epochs: 3
  batch_size: 1
  learning_rate: 2e-4
  logging_steps: 10
  save_steps: 100
  lora_r: 8
  lora_alpha: 32
  lora_dropout: 0.05

wandb:
  enabled: true
  project: llama-finetune
  run_name: lora-training
