# Configuration for LoRA fine-tuning
model:
  # Path to the base model weights (local path or HF repo)
  base_model_path: /workspace/data/mygitstuff/llama3_fine_tuning/models/base_3_1_8b
  hf_token: null  # Optional Hugging Face token

training:
  datasets:
    - /workspace/data/mygitstuff/llama3_fine_tuning/datasets/F01_preprocessed_SCHEMA_DOCS.jsonl
    - /workspace/data/mygitstuff/llama3_fine_tuning/datasets/F01_preprocessed_RELATIONSHIPS.jsonl
    - /workspace/data/mygitstuff/llama3_fine_tuning/datasets/F01_preprocessed_SINGLETABLE_WSCHEMA.jsonl
  output_dir: /workspace/data/mygitstuff/checkpoints/lora_run01
  num_epochs: 3
  batch_size: 1
  learning_rate: 2e-4
  logging_steps: 10
  save_steps: 100
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  gradient_accumulation_steps: 4

wandb:
  enabled: true
  project: llama-finetune
  run_name: lora-training
